/**
 * Server-only helpers for the MANOVIK project workspace.
 * Kept out of *.functions.ts so the server-fn splitter never drops them.
 */

export type StarterFile = { path: string; content: string; language: string };

export const MAX_FILES_PER_PROJECT = 200;
export const MAX_FILE_BYTES = 200_000;

export function languageForPath(path: string): string {
  const ext = path.split(".").pop()?.toLowerCase() ?? "";
  const map: Record<string, string> = {
    ts: "typescript",
    tsx: "tsx",
    js: "javascript",
    jsx: "jsx",
    json: "json",
    css: "css",
    html: "html",
    md: "markdown",
    py: "python",
    sql: "sql",
    sh: "bash",
    yml: "yaml",
    yaml: "yaml",
  };
  return map[ext] ?? "plaintext";
}

export function normalizePath(input: string): string {
  const cleaned = input
    .trim()
    .replace(/\\/g, "/")
    .replace(/^\/+/, "")
    .replace(/\/{2,}/g, "/");
  if (!cleaned) throw new Error("File path is required");
  if (cleaned.includes("..")) throw new Error("Path traversal is not allowed");
  if (cleaned.length > 240) throw new Error("File path is too long");
  if (!/^[\w./@-]+$/.test(cleaned)) throw new Error("File path has invalid characters");
  return cleaned;
}

export function starterFiles(framework: string): StarterFile[] {
  if (framework === "node") {
    return [
      {
        path: "index.js",
        language: "javascript",
        content: `export function main() {\n  return "Hello from MANOVIK";\n}\n\nconsole.log(main());\n`,
      },
      {
        path: "package.json",
        language: "json",
        content: `{\n  "name": "manovik-app",\n  "type": "module",\n  "version": "0.1.0"\n}\n`,
      },
    ];
  }
  if (framework === "python") {
    return [
      {
        path: "main.py",
        language: "python",
        content: `def main() -> str:\n    return "Hello from MANOVIK"\n\n\nif __name__ == "__main__":\n    print(main())\n`,
      },
    ];
  }
  return [
    {
      path: "src/App.tsx",
      language: "tsx",
      content: `export default function App() {\n  return (\n    <main style={{ fontFamily: "system-ui", padding: 32 }}>\n      <h1>Hello from MANOVIK</h1>\n      <p>Edit src/App.tsx and hit Run.</p>\n    </main>\n  );\n}\n`,
    },
    {
      path: "src/main.tsx",
      language: "tsx",
      content: `import App from "./App";\n\nexport { App };\n`,
    },
    {
      path: "README.md",
      language: "markdown",
      content: `# MANOVIK project\n\nGenerated by MANOVIK. Build and run from the project workspace.\n`,
    },
  ];
}

export type BuildFile = { path: string; content: string };
export type BuildResult = {
  status: "success" | "failed";
  exitCode: number;
  logs: string;
  durationMs: number;
  stats: { files: number; bytes: number; errors: number; warnings: number };
};

const PAIRS: Record<string, string> = { "}": "{", ")": "(", "]": "[" };

function balanceErrors(content: string): string[] {
  const stack: string[] = [];
  const errors: string[] = [];
  let line = 1;
  let inString: string | null = null;
  let inLineComment = false;
  let inBlockComment = false;
  for (let i = 0; i < content.length; i++) {
    const ch = content[i]!;
    const next = content[i + 1];
    if (ch === "\n") {
      line++;
      inLineComment = false;
      continue;
    }
    if (inLineComment) continue;
    if (inBlockComment) {
      if (ch === "*" && next === "/") {
        inBlockComment = false;
        i++;
      }
      continue;
    }
    if (inString) {
      if (ch === "\\") i++;
      else if (ch === inString) inString = null;
      continue;
    }
    if (ch === "/" && next === "/") {
      inLineComment = true;
      i++;
      continue;
    }
    if (ch === "/" && next === "*") {
      inBlockComment = true;
      i++;
      continue;
    }
    if (ch === '"' || ch === "'" || ch === "`") {
      inString = ch;
      continue;
    }
    if (ch === "{" || ch === "(" || ch === "[") stack.push(ch);
    else if (ch === "}" || ch === ")" || ch === "]") {
      const open = stack.pop();
      if (open !== PAIRS[ch]) errors.push(`line ${line}: unexpected "${ch}"`);
    }
  }
  if (inString) errors.push("unterminated string literal");
  if (inBlockComment) errors.push("unterminated block comment");
  if (stack.length) errors.push(`${stack.length} unclosed "${stack[stack.length - 1]}"`);
  return errors;
}

function relativeImports(content: string): string[] {
  const out: string[] = [];
  const re = /(?:from|import)\s+["'](\.[^"']+)["']/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(content))) out.push(m[1]!);
  return out;
}

function resolveRelative(fromPath: string, spec: string, known: Set<string>): string | null {
  const base = fromPath.split("/").slice(0, -1);
  for (const part of spec.split("/")) {
    if (part === "." || part === "") continue;
    if (part === "..") base.pop();
    else base.push(part);
  }
  const target = base.join("/");
  const candidates = [
    target,
    `${target}.ts`,
    `${target}.tsx`,
    `${target}.js`,
    `${target}.jsx`,
    `${target}/index.ts`,
    `${target}/index.tsx`,
  ];
  return candidates.find((c) => known.has(c)) ?? null;
}

/**
 * Deterministic server-side build/run pass. Runs entirely in the Worker
 * runtime (no child processes): validates structure, syntax balance and
 * local module resolution, and emits real logs that are persisted per build.
 */
export function runBuild(files: BuildFile[], command: string, entryPath: string): BuildResult {
  const started = Date.now();
  const logs: string[] = [];
  const known = new Set(files.map((f) => f.path));
  let errors = 0;
  let warnings = 0;
  const bytes = files.reduce((n, f) => n + f.content.length, 0);

  logs.push(`$ manovik ${command}`);
  logs.push(`> resolving ${files.length} file(s), ${(bytes / 1024).toFixed(1)} kB`);

  if (files.length === 0) {
    errors++;
    logs.push("error: project has no files");
  }

  const codeFiles = files.filter((f) => /\.(ts|tsx|js|jsx|json|css)$/.test(f.path));
  for (const file of codeFiles) {
    if (file.path.endsWith(".json")) {
      try {
        JSON.parse(file.content);
      } catch (e) {
        errors++;
        logs.push(`error ${file.path}: invalid JSON — ${(e as Error).message}`);
      }
      continue;
    }
    const issues = balanceErrors(file.content);
    for (const issue of issues) {
      errors++;
      logs.push(`error ${file.path}: ${issue}`);
    }
    for (const spec of relativeImports(file.content)) {
      if (!resolveRelative(file.path, spec, known)) {
        errors++;
        logs.push(`error ${file.path}: cannot resolve import "${spec}"`);
      }
    }
    if (/\bconsole\.log\(/.test(file.content) && command === "build") {
      warnings++;
      logs.push(`warn ${file.path}: console.log left in production build`);
    }
    if (file.content.length > MAX_FILE_BYTES) {
      warnings++;
      logs.push(`warn ${file.path}: file is unusually large`);
    }
  }

  if (entryPath && !known.has(entryPath)) {
    warnings++;
    logs.push(`warn: entry "${entryPath}" not found in project`);
  }

  const durationMs = Date.now() - started;
  if (errors === 0) {
    logs.push(`> ${command} succeeded in ${durationMs}ms (${warnings} warning(s))`);
  } else {
    logs.push(`> ${command} failed with ${errors} error(s), ${warnings} warning(s)`);
  }

  return {
    status: errors === 0 ? "success" : "failed",
    exitCode: errors === 0 ? 0 : 1,
    logs: logs.join("\n"),
    durationMs,
    stats: { files: files.length, bytes, errors, warnings },
  };
}

/** Build a self-contained HTML document for the live preview iframe. */
export function previewDocument(files: BuildFile[], entryPath: string): string {
  const html = files.find((f) => f.path.endsWith(".html"));
  if (html) return html.content;
  const css = files
    .filter((f) => f.path.endsWith(".css"))
    .map((f) => f.content)
    .join("\n");
  const entry = files.find((f) => f.path === entryPath) ?? files[0];
  const escaped = (entry?.content ?? "// empty project")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
  return `<!doctype html><html><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width,initial-scale=1" /><style>
  :root{color-scheme:dark}
  body{margin:0;font:14px/1.6 ui-monospace,SFMono-Regular,Menlo,monospace;background:#0b0b0f;color:#e6e6ef;padding:20px}
  h1{font:600 15px/1.4 system-ui;margin:0 0 12px;color:#a78bfa}
  pre{white-space:pre-wrap;word-break:break-word;margin:0}
  ${css}
</style></head><body><h1>${entry?.path ?? "preview"}</h1><pre>${escaped}</pre></body></html>`;
}
