#!/usr/bin/env bash
# Generate the JWT signing keys for the self-hosted Supabase stack.
#
# Usage:
#   ./scripts/gen-supabase-keys.sh >> .env
#
# If JWT_SECRET is set in the environment it is reused; otherwise a fresh
# 256-bit secret is generated. The anon and service_role keys are HS256 JWTs
# signed with that secret (10-year expiry, like Supabase Cloud keys).
#
# Prints .env-ready assignments to stdout. Keep the output private — it
# contains the signing keys for your stack.
#
# Requires: openssl, python3

set -euo pipefail

if [ -n "${JWT_SECRET:-}" ]; then
  SECRET="$JWT_SECRET"
else
  SECRET="$(openssl rand -hex 32)"
fi

KEYS="$(python3 - "$SECRET" <<'PY'
import base64
import hashlib
import hmac
import json
import sys
import time

secret = sys.argv[1].encode()


def b64url(data: bytes) -> bytes:
    return base64.urlsafe_b64encode(data).rstrip(b"=")


def sign(payload: dict) -> str:
    header = b64url(json.dumps({"alg": "HS256", "typ": "JWT"}).encode())
    body = b64url(json.dumps(payload, separators=(",", ":")).encode())
    sig = b64url(hmac.new(secret, header + b"." + body, hashlib.sha256).digest())
    return (header + b"." + body + b"." + sig).decode()


now = int(time.time())
exp = now + 10 * 365 * 24 * 3600  # 10 years, like Supabase Cloud keys
print(sign({"role": "anon", "iss": "supabase", "iat": now, "exp": exp}))
print(sign({"role": "service_role", "iss": "supabase", "iat": now, "exp": exp}))
PY
)"

ANON_KEY="$(printf '%s\n' "$KEYS" | sed -n '1p')"
SERVICE_KEY="$(printf '%s\n' "$KEYS" | sed -n '2p')"

cat <<EOF
# --- Generated by scripts/gen-supabase-keys.sh — keep private ---
JWT_SECRET=$SECRET
SUPABASE_PUBLISHABLE_KEY=$ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_KEY
EOF
