/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VsWindsurfRouteImport } from './routes/vs-windsurf'
import { Route as VsReplitAgentRouteImport } from './routes/vs-replit-agent'
import { Route as VsGithubCopilotRouteImport } from './routes/vs-github-copilot'
import { Route as VsDevinRouteImport } from './routes/vs-devin'
import { Route as VsCursorRouteImport } from './routes/vs-cursor'
import { Route as VsClineVsWindsurfRouteImport } from './routes/vs-cline-vs-windsurf'
import { Route as VsClineRouteImport } from './routes/vs-cline'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SeoRouteImport } from './routes/seo'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BestAiCodingAgentRouteImport } from './routes/best-ai-coding-agent'
import { Route as BalanceRouteImport } from './routes/balance'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AiCodingAssistantRouteImport } from './routes/ai-coding-assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceiptIdRouteImport } from './routes/receipt.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as BlogWillAiReplaceSoftwareEngineersRouteImport } from './routes/blog.will-ai-replace-software-engineers'
import { Route as BlogSelfHostingAiWithOllamaRouteImport } from './routes/blog.self-hosting-ai-with-ollama'
import { Route as BlogMcpGuideRouteImport } from './routes/blog.mcp-guide'
import { Route as BlogBestAiCodingAgentsRouteImport } from './routes/blog.best-ai-coding-agents'
import { Route as BlogAiPricingComparisonRouteImport } from './routes/blog.ai-pricing-comparison'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as ApiAuthMagicLinkRouteImport } from './routes/api/auth/magic-link'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksSecurityScanRouteImport } from './routes/api/public/hooks/security-scan'
import { Route as ApiPublicHooksResubmitSitemapRouteImport } from './routes/api/public/hooks/resubmit-sitemap'
import { Route as ApiPublicHooksManovikSelfUpdateRouteImport } from './routes/api/public/hooks/manovik-self-update'

const VsWindsurfRoute = VsWindsurfRouteImport.update({
  id: '/vs-windsurf',
  path: '/vs-windsurf',
  getParentRoute: () => rootRouteImport,
} as any)
const VsReplitAgentRoute = VsReplitAgentRouteImport.update({
  id: '/vs-replit-agent',
  path: '/vs-replit-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const VsGithubCopilotRoute = VsGithubCopilotRouteImport.update({
  id: '/vs-github-copilot',
  path: '/vs-github-copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const VsDevinRoute = VsDevinRouteImport.update({
  id: '/vs-devin',
  path: '/vs-devin',
  getParentRoute: () => rootRouteImport,
} as any)
const VsCursorRoute = VsCursorRouteImport.update({
  id: '/vs-cursor',
  path: '/vs-cursor',
  getParentRoute: () => rootRouteImport,
} as any)
const VsClineVsWindsurfRoute = VsClineVsWindsurfRouteImport.update({
  id: '/vs-cline-vs-windsurf',
  path: '/vs-cline-vs-windsurf',
  getParentRoute: () => rootRouteImport,
} as any)
const VsClineRoute = VsClineRouteImport.update({
  id: '/vs-cline',
  path: '/vs-cline',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRoute = SeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BestAiCodingAgentRoute = BestAiCodingAgentRouteImport.update({
  id: '/best-ai-coding-agent',
  path: '/best-ai-coding-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const BalanceRoute = BalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCodingAssistantRoute = AiCodingAssistantRouteImport.update({
  id: '/ai-coding-assistant',
  path: '/ai-coding-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptIdRoute = ReceiptIdRouteImport.update({
  id: '/receipt/$id',
  path: '/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWillAiReplaceSoftwareEngineersRoute =
  BlogWillAiReplaceSoftwareEngineersRouteImport.update({
    id: '/blog/will-ai-replace-software-engineers',
    path: '/blog/will-ai-replace-software-engineers',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogSelfHostingAiWithOllamaRoute =
  BlogSelfHostingAiWithOllamaRouteImport.update({
    id: '/blog/self-hosting-ai-with-ollama',
    path: '/blog/self-hosting-ai-with-ollama',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogMcpGuideRoute = BlogMcpGuideRouteImport.update({
  id: '/blog/mcp-guide',
  path: '/blog/mcp-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBestAiCodingAgentsRoute = BlogBestAiCodingAgentsRouteImport.update({
  id: '/blog/best-ai-coding-agents',
  path: '/blog/best-ai-coding-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAiPricingComparisonRoute = BlogAiPricingComparisonRouteImport.update({
  id: '/blog/ai-pricing-comparison',
  path: '/blog/ai-pricing-comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthMagicLinkRoute = ApiAuthMagicLinkRouteImport.update({
  id: '/api/auth/magic-link',
  path: '/api/auth/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSecurityScanRoute =
  ApiPublicHooksSecurityScanRouteImport.update({
    id: '/api/public/hooks/security-scan',
    path: '/api/public/hooks/security-scan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksResubmitSitemapRoute =
  ApiPublicHooksResubmitSitemapRouteImport.update({
    id: '/api/public/hooks/resubmit-sitemap',
    path: '/api/public/hooks/resubmit-sitemap',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksManovikSelfUpdateRoute =
  ApiPublicHooksManovikSelfUpdateRouteImport.update({
    id: '/api/public/hooks/manovik-self-update',
    path: '/api/public/hooks/manovik-self-update',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-coding-assistant': typeof AiCodingAssistantRoute
  '/audit': typeof AuditRoute
  '/balance': typeof BalanceRoute
  '/best-ai-coding-agent': typeof BestAiCodingAgentRoute
  '/billing': typeof BillingRoute
  '/chat': typeof ChatRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/seo': typeof SeoRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/students': typeof StudentsRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vs-cline': typeof VsClineRoute
  '/vs-cline-vs-windsurf': typeof VsClineVsWindsurfRoute
  '/vs-cursor': typeof VsCursorRoute
  '/vs-devin': typeof VsDevinRoute
  '/vs-github-copilot': typeof VsGithubCopilotRoute
  '/vs-replit-agent': typeof VsReplitAgentRoute
  '/vs-windsurf': typeof VsWindsurfRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/ai-pricing-comparison': typeof BlogAiPricingComparisonRoute
  '/blog/best-ai-coding-agents': typeof BlogBestAiCodingAgentsRoute
  '/blog/mcp-guide': typeof BlogMcpGuideRoute
  '/blog/self-hosting-ai-with-ollama': typeof BlogSelfHostingAiWithOllamaRoute
  '/blog/will-ai-replace-software-engineers': typeof BlogWillAiReplaceSoftwareEngineersRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/auth/magic-link': typeof ApiAuthMagicLinkRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/manovik-self-update': typeof ApiPublicHooksManovikSelfUpdateRoute
  '/api/public/hooks/resubmit-sitemap': typeof ApiPublicHooksResubmitSitemapRoute
  '/api/public/hooks/security-scan': typeof ApiPublicHooksSecurityScanRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-coding-assistant': typeof AiCodingAssistantRoute
  '/audit': typeof AuditRoute
  '/balance': typeof BalanceRoute
  '/best-ai-coding-agent': typeof BestAiCodingAgentRoute
  '/billing': typeof BillingRoute
  '/chat': typeof ChatRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/seo': typeof SeoRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/students': typeof StudentsRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vs-cline': typeof VsClineRoute
  '/vs-cline-vs-windsurf': typeof VsClineVsWindsurfRoute
  '/vs-cursor': typeof VsCursorRoute
  '/vs-devin': typeof VsDevinRoute
  '/vs-github-copilot': typeof VsGithubCopilotRoute
  '/vs-replit-agent': typeof VsReplitAgentRoute
  '/vs-windsurf': typeof VsWindsurfRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/ai-pricing-comparison': typeof BlogAiPricingComparisonRoute
  '/blog/best-ai-coding-agents': typeof BlogBestAiCodingAgentsRoute
  '/blog/mcp-guide': typeof BlogMcpGuideRoute
  '/blog/self-hosting-ai-with-ollama': typeof BlogSelfHostingAiWithOllamaRoute
  '/blog/will-ai-replace-software-engineers': typeof BlogWillAiReplaceSoftwareEngineersRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/auth/magic-link': typeof ApiAuthMagicLinkRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/manovik-self-update': typeof ApiPublicHooksManovikSelfUpdateRoute
  '/api/public/hooks/resubmit-sitemap': typeof ApiPublicHooksResubmitSitemapRoute
  '/api/public/hooks/security-scan': typeof ApiPublicHooksSecurityScanRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-coding-assistant': typeof AiCodingAssistantRoute
  '/audit': typeof AuditRoute
  '/balance': typeof BalanceRoute
  '/best-ai-coding-agent': typeof BestAiCodingAgentRoute
  '/billing': typeof BillingRoute
  '/chat': typeof ChatRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/seo': typeof SeoRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/students': typeof StudentsRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vs-cline': typeof VsClineRoute
  '/vs-cline-vs-windsurf': typeof VsClineVsWindsurfRoute
  '/vs-cursor': typeof VsCursorRoute
  '/vs-devin': typeof VsDevinRoute
  '/vs-github-copilot': typeof VsGithubCopilotRoute
  '/vs-replit-agent': typeof VsReplitAgentRoute
  '/vs-windsurf': typeof VsWindsurfRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/ai-pricing-comparison': typeof BlogAiPricingComparisonRoute
  '/blog/best-ai-coding-agents': typeof BlogBestAiCodingAgentsRoute
  '/blog/mcp-guide': typeof BlogMcpGuideRoute
  '/blog/self-hosting-ai-with-ollama': typeof BlogSelfHostingAiWithOllamaRoute
  '/blog/will-ai-replace-software-engineers': typeof BlogWillAiReplaceSoftwareEngineersRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/auth/magic-link': typeof ApiAuthMagicLinkRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/manovik-self-update': typeof ApiPublicHooksManovikSelfUpdateRoute
  '/api/public/hooks/resubmit-sitemap': typeof ApiPublicHooksResubmitSitemapRoute
  '/api/public/hooks/security-scan': typeof ApiPublicHooksSecurityScanRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-coding-assistant'
    | '/audit'
    | '/balance'
    | '/best-ai-coding-agent'
    | '/billing'
    | '/chat'
    | '/connect'
    | '/contact'
    | '/login'
    | '/mcp'
    | '/privacy'
    | '/refund'
    | '/seo'
    | '/setup'
    | '/sitemap.xml'
    | '/students'
    | '/terms'
    | '/unsubscribe'
    | '/vs-cline'
    | '/vs-cline-vs-windsurf'
    | '/vs-cursor'
    | '/vs-devin'
    | '/vs-github-copilot'
    | '/vs-replit-agent'
    | '/vs-windsurf'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/auth/callback'
    | '/blog/ai-pricing-comparison'
    | '/blog/best-ai-coding-agents'
    | '/blog/mcp-guide'
    | '/blog/self-hosting-ai-with-ollama'
    | '/blog/will-ai-replace-software-engineers'
    | '/email/unsubscribe'
    | '/receipt/$id'
    | '/.mcp/invoke-tool/$tool'
    | '/api/auth/magic-link'
    | '/api/public/razorpay-webhook'
    | '/lovable/email/suppression'
    | '/api/public/hooks/manovik-self-update'
    | '/api/public/hooks/resubmit-sitemap'
    | '/api/public/hooks/security-scan'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-coding-assistant'
    | '/audit'
    | '/balance'
    | '/best-ai-coding-agent'
    | '/billing'
    | '/chat'
    | '/connect'
    | '/contact'
    | '/login'
    | '/mcp'
    | '/privacy'
    | '/refund'
    | '/seo'
    | '/setup'
    | '/sitemap.xml'
    | '/students'
    | '/terms'
    | '/unsubscribe'
    | '/vs-cline'
    | '/vs-cline-vs-windsurf'
    | '/vs-cursor'
    | '/vs-devin'
    | '/vs-github-copilot'
    | '/vs-replit-agent'
    | '/vs-windsurf'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/auth/callback'
    | '/blog/ai-pricing-comparison'
    | '/blog/best-ai-coding-agents'
    | '/blog/mcp-guide'
    | '/blog/self-hosting-ai-with-ollama'
    | '/blog/will-ai-replace-software-engineers'
    | '/email/unsubscribe'
    | '/receipt/$id'
    | '/.mcp/invoke-tool/$tool'
    | '/api/auth/magic-link'
    | '/api/public/razorpay-webhook'
    | '/lovable/email/suppression'
    | '/api/public/hooks/manovik-self-update'
    | '/api/public/hooks/resubmit-sitemap'
    | '/api/public/hooks/security-scan'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/ai-coding-assistant'
    | '/audit'
    | '/balance'
    | '/best-ai-coding-agent'
    | '/billing'
    | '/chat'
    | '/connect'
    | '/contact'
    | '/login'
    | '/mcp'
    | '/privacy'
    | '/refund'
    | '/seo'
    | '/setup'
    | '/sitemap.xml'
    | '/students'
    | '/terms'
    | '/unsubscribe'
    | '/vs-cline'
    | '/vs-cline-vs-windsurf'
    | '/vs-cursor'
    | '/vs-devin'
    | '/vs-github-copilot'
    | '/vs-replit-agent'
    | '/vs-windsurf'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/auth/callback'
    | '/blog/ai-pricing-comparison'
    | '/blog/best-ai-coding-agents'
    | '/blog/mcp-guide'
    | '/blog/self-hosting-ai-with-ollama'
    | '/blog/will-ai-replace-software-engineers'
    | '/email/unsubscribe'
    | '/receipt/$id'
    | '/.mcp/invoke-tool/$tool'
    | '/api/auth/magic-link'
    | '/api/public/razorpay-webhook'
    | '/lovable/email/suppression'
    | '/api/public/hooks/manovik-self-update'
    | '/api/public/hooks/resubmit-sitemap'
    | '/api/public/hooks/security-scan'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiCodingAssistantRoute: typeof AiCodingAssistantRoute
  AuditRoute: typeof AuditRoute
  BalanceRoute: typeof BalanceRoute
  BestAiCodingAgentRoute: typeof BestAiCodingAgentRoute
  BillingRoute: typeof BillingRoute
  ChatRoute: typeof ChatRoute
  ConnectRoute: typeof ConnectRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  SeoRoute: typeof SeoRoute
  SetupRoute: typeof SetupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudentsRoute: typeof StudentsRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VsClineRoute: typeof VsClineRoute
  VsClineVsWindsurfRoute: typeof VsClineVsWindsurfRoute
  VsCursorRoute: typeof VsCursorRoute
  VsDevinRoute: typeof VsDevinRoute
  VsGithubCopilotRoute: typeof VsGithubCopilotRoute
  VsReplitAgentRoute: typeof VsReplitAgentRoute
  VsWindsurfRoute: typeof VsWindsurfRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BlogAiPricingComparisonRoute: typeof BlogAiPricingComparisonRoute
  BlogBestAiCodingAgentsRoute: typeof BlogBestAiCodingAgentsRoute
  BlogMcpGuideRoute: typeof BlogMcpGuideRoute
  BlogSelfHostingAiWithOllamaRoute: typeof BlogSelfHostingAiWithOllamaRoute
  BlogWillAiReplaceSoftwareEngineersRoute: typeof BlogWillAiReplaceSoftwareEngineersRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ReceiptIdRoute: typeof ReceiptIdRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiAuthMagicLinkRoute: typeof ApiAuthMagicLinkRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksManovikSelfUpdateRoute: typeof ApiPublicHooksManovikSelfUpdateRoute
  ApiPublicHooksResubmitSitemapRoute: typeof ApiPublicHooksResubmitSitemapRoute
  ApiPublicHooksSecurityScanRoute: typeof ApiPublicHooksSecurityScanRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vs-windsurf': {
      id: '/vs-windsurf'
      path: '/vs-windsurf'
      fullPath: '/vs-windsurf'
      preLoaderRoute: typeof VsWindsurfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs-replit-agent': {
      id: '/vs-replit-agent'
      path: '/vs-replit-agent'
      fullPath: '/vs-replit-agent'
      preLoaderRoute: typeof VsReplitAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs-github-copilot': {
      id: '/vs-github-copilot'
      path: '/vs-github-copilot'
      fullPath: '/vs-github-copilot'
      preLoaderRoute: typeof VsGithubCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs-devin': {
      id: '/vs-devin'
      path: '/vs-devin'
      fullPath: '/vs-devin'
      preLoaderRoute: typeof VsDevinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs-cursor': {
      id: '/vs-cursor'
      path: '/vs-cursor'
      fullPath: '/vs-cursor'
      preLoaderRoute: typeof VsCursorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs-cline-vs-windsurf': {
      id: '/vs-cline-vs-windsurf'
      path: '/vs-cline-vs-windsurf'
      fullPath: '/vs-cline-vs-windsurf'
      preLoaderRoute: typeof VsClineVsWindsurfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs-cline': {
      id: '/vs-cline'
      path: '/vs-cline'
      fullPath: '/vs-cline'
      preLoaderRoute: typeof VsClineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo': {
      id: '/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof SeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-ai-coding-agent': {
      id: '/best-ai-coding-agent'
      path: '/best-ai-coding-agent'
      fullPath: '/best-ai-coding-agent'
      preLoaderRoute: typeof BestAiCodingAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balance': {
      id: '/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof BalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-coding-assistant': {
      id: '/ai-coding-assistant'
      path: '/ai-coding-assistant'
      fullPath: '/ai-coding-assistant'
      preLoaderRoute: typeof AiCodingAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$id': {
      id: '/receipt/$id'
      path: '/receipt/$id'
      fullPath: '/receipt/$id'
      preLoaderRoute: typeof ReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/will-ai-replace-software-engineers': {
      id: '/blog/will-ai-replace-software-engineers'
      path: '/blog/will-ai-replace-software-engineers'
      fullPath: '/blog/will-ai-replace-software-engineers'
      preLoaderRoute: typeof BlogWillAiReplaceSoftwareEngineersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/self-hosting-ai-with-ollama': {
      id: '/blog/self-hosting-ai-with-ollama'
      path: '/blog/self-hosting-ai-with-ollama'
      fullPath: '/blog/self-hosting-ai-with-ollama'
      preLoaderRoute: typeof BlogSelfHostingAiWithOllamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/mcp-guide': {
      id: '/blog/mcp-guide'
      path: '/blog/mcp-guide'
      fullPath: '/blog/mcp-guide'
      preLoaderRoute: typeof BlogMcpGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/best-ai-coding-agents': {
      id: '/blog/best-ai-coding-agents'
      path: '/blog/best-ai-coding-agents'
      fullPath: '/blog/best-ai-coding-agents'
      preLoaderRoute: typeof BlogBestAiCodingAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/ai-pricing-comparison': {
      id: '/blog/ai-pricing-comparison'
      path: '/blog/ai-pricing-comparison'
      fullPath: '/blog/ai-pricing-comparison'
      preLoaderRoute: typeof BlogAiPricingComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/magic-link': {
      id: '/api/auth/magic-link'
      path: '/api/auth/magic-link'
      fullPath: '/api/auth/magic-link'
      preLoaderRoute: typeof ApiAuthMagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/security-scan': {
      id: '/api/public/hooks/security-scan'
      path: '/api/public/hooks/security-scan'
      fullPath: '/api/public/hooks/security-scan'
      preLoaderRoute: typeof ApiPublicHooksSecurityScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/resubmit-sitemap': {
      id: '/api/public/hooks/resubmit-sitemap'
      path: '/api/public/hooks/resubmit-sitemap'
      fullPath: '/api/public/hooks/resubmit-sitemap'
      preLoaderRoute: typeof ApiPublicHooksResubmitSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/manovik-self-update': {
      id: '/api/public/hooks/manovik-self-update'
      path: '/api/public/hooks/manovik-self-update'
      fullPath: '/api/public/hooks/manovik-self-update'
      preLoaderRoute: typeof ApiPublicHooksManovikSelfUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiCodingAssistantRoute: AiCodingAssistantRoute,
  AuditRoute: AuditRoute,
  BalanceRoute: BalanceRoute,
  BestAiCodingAgentRoute: BestAiCodingAgentRoute,
  BillingRoute: BillingRoute,
  ChatRoute: ChatRoute,
  ConnectRoute: ConnectRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  SeoRoute: SeoRoute,
  SetupRoute: SetupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudentsRoute: StudentsRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VsClineRoute: VsClineRoute,
  VsClineVsWindsurfRoute: VsClineVsWindsurfRoute,
  VsCursorRoute: VsCursorRoute,
  VsDevinRoute: VsDevinRoute,
  VsGithubCopilotRoute: VsGithubCopilotRoute,
  VsReplitAgentRoute: VsReplitAgentRoute,
  VsWindsurfRoute: VsWindsurfRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BlogAiPricingComparisonRoute: BlogAiPricingComparisonRoute,
  BlogBestAiCodingAgentsRoute: BlogBestAiCodingAgentsRoute,
  BlogMcpGuideRoute: BlogMcpGuideRoute,
  BlogSelfHostingAiWithOllamaRoute: BlogSelfHostingAiWithOllamaRoute,
  BlogWillAiReplaceSoftwareEngineersRoute:
    BlogWillAiReplaceSoftwareEngineersRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ReceiptIdRoute: ReceiptIdRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiAuthMagicLinkRoute: ApiAuthMagicLinkRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksManovikSelfUpdateRoute: ApiPublicHooksManovikSelfUpdateRoute,
  ApiPublicHooksResubmitSitemapRoute: ApiPublicHooksResubmitSitemapRoute,
  ApiPublicHooksSecurityScanRoute: ApiPublicHooksSecurityScanRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
